# Linear Regression Plots

Source: <https://rpubs.com/pjozefek/576206>

```{r}
pacman::p_load(tidyverse, magrittr, here, janitor, plot3D, rayshader)
```

```{r}
data <- read_csv(here("datasets", "advertising.csv")) %>% clean_names()
```

## Plot3D for regression plane

```{r}
# set the x, y, and z variables
x <- data$radio
y <- data$tv
z <- data$sales

# compute the linear regression 
fit <- lm(z ~ x + y)

# create a grid from the x and y values (min to max) 
# and predict values for every point
# (this will become the regression plane)
grid.lines = 40

x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)

xy <- expand.grid( x = x.pred, y = y.pred)

z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, 
                 ncol = grid.lines)

# create the fitted points for droplines to the surface
fitpoints <- predict(fit)

# scatter plot with regression plane
scatter3D(x, y, z, 
          pch = 19, 
          cex = .8,
          col = "red", 
          theta = 50, 
          phi = 25, 
          bty = "b",
          xlab = "Radio", 
          ylab = "TV", 
          zlab = "Sales",  
          surf = list(x = x.pred, 
                      y = y.pred, 
                      z = z.pred,  
                      facets = TRUE, 
                      fit = fitpoints, 
                      col = ramp.col(col = c("dodgerblue3","seagreen2"), 
                                     n = 300, alpha = 0.9), 
                      border = "black"), 
          main = "Advertising")
```

## A bit of a digression: Rayshader

```{r}
ggdiamonds <- 
  ggplot(diamonds) +
  stat_density_2d(aes(x = x, y = depth, fill = stat(nlevel)), 
                  geom = "polygon", n = 200, bins = 50,contour = TRUE) +
  facet_wrap(clarity~.) +
  scale_fill_viridis_c(option = "A")

plot_gg(ggdiamonds, 
        width = 10, 
        height = 10, 
        multicore = TRUE, 
        scale = 500, 
        zoom = 0.7, 
        theta = 10, 
        phi = 30, 
        windowsize = c(800, 800))

Sys.sleep(0.2)
render_snapshot(clear = TRUE)
```
